### ISSUE TITLE
space in scm:connection

### ISSUE THREAD

**Issue by MasseGuillaume** [urbas/play-essentials#2]
There is a space between `scm:git:` and the github url.

```
<cm>
        <connection>scm:git: git@github.com:urbas/play-essentials.git </connection>
        <developerConnection>scm:git: git@github.com:urbas/play-essentials.git </developerConnection>
        <url> https://github.com/urbas/play-essentials </url>
 </scm>
```

http://search.maven.org/#artifactdetails%7Csi.urbas%7Cpless_2.11%7C0.0.16%7Cjar

**Comment by urbas** [comment]
Hey @MasseGuillaume, thanks a bunch for reporting this!

This issue has been addressed here: https://github.com/urbas/play-essentials/commit/f22bbedadb4e6e0bb2da781998feeb215cc90d24#diff-65f2c845d9ed0d50ea3dfce6373c56b7R173

Unfortunately, I haven't published this new version yet. Please let me know if you need a new version.

In the meantime, I will close this issue.

**Comment by MasseGuillaume** [comment]
Ah ops sorry for bugging you ;-).
